from .settings_plot import SettingsPlot
from .settings_scatter import SettingsScatter
from .settings_regression_figure import SettingsRegressionFigure
from .settings_speed_comparison_figure import SettingsSpeedComparisonFigure
from .settings_trace_figure import SettingsTraceFigure
from .settings_triangle_figure import SettingsTriangleFigure
from .settings_sequence_figure import SettingsSequenceFigure
from .settings_cardinality_figure import SettingsCardinalityFigure
from .settings_paper_figure_bivariate import SettingsPaperFigureBivariate

