from visualization.triangle_figure import TriangleFigure, BivariatePlot, PlotSettings, ScatterSettings, TriangleSettings
from visualization.regression_figure import RegressionFigure, RegressionSettings, TransformationPlotSettings, DataPlotSettings
from visualization.speed_comparison_figure import SpeedComparisonFigure, SpeedComparisonSettings
from visualization.trace_figure import TraceFigure, TraceSettings

