from visualization.triangle_figure import TriangleFigure, BivariatePlot, PlotSettings, ScatterSettings, TriangleSettings
from visualization.regression_figure import RegressionFigure, RegressionPlot, RegressionSettings, RegressionPlotSettings
from visualization.speed_comparison_figure import SpeedComparisonFigure, SpeedComparisonSettings

